version: '3.9'

services:

  nginx:
    image: nginx:mainline
    ports:
      - 2000:2000
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./certs/:/usr/share/certs/"
    depends_on:
      - frontend
      - app
  pgdb:
    image: 'postgres'
    restart: always
    env_file:
      - ./env/sql.env
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./sql/scripts:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data
  app:
    image: 'spring-boot-app:latest'
    build:
      dockerfile: production/Dockerfile
    container_name: spring-boot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/sfg_prod?reWriteBatchedInserts=true
    ports:
      - 8080:8080
    command: [bootRun]
    depends_on:
      - pgdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    depends_on:
      - app
  frontend:
      image: recycleeyesnapshot/client:latest
      restart: always
      container_name: react-app
      depends_on:
        - adminer
      tty: true
volumes:
  scripts:
  data: